apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ypgony3wv-python 
  janus-idp.io/tekton: ypgony3wv-python
  backstage.io/kubernetes-id: ypgony3wv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ypgony3wv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml